import { Theme } from '@mui/material';

const categoryStyles = (theme: Theme) => ({
  categoryBox1: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
  },
  categoryBox1ChildImg: {
    width: '100%',
    maxWidth: 400,
  },
  mainCategoryAddButton: {
    border: '3px dashed',
    mt: 2,
  },
  categorySearchInputBox: {
    padding: 0,
    marginBottom: '1.2rem',

    '& .MuiOutlinedInput-input::placeholder': {
      color: theme.palette.text.primary,
      opacity: 1,
    },
  },
  categoryContainerItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    mb: 2,
    padding: 1,
    cursor: 'pointer',
    borderRadius: 2,
  },
  categoryContainerItemText: {
    fontWeight: 600,
    fontSize: '1rem',
  },
  categoryParentContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    mt: 0,
    padding: 0,
  },
  sectionContainerChild: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '1rem',
  },

  sectionContainer: {
    width: '300px',
    height: '600px',
    backgroundColor: theme.palette.primary.main,
    borderRadius: 3,
    padding: '16px',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: 3,
    overflowY: 'auto',
    marginRight: '2rem',
  },
  categoryAddIcon: {
    borderRadius: '1rem',
    backgroundColor: theme.palette.text.primary,
    color: theme.palette.primary.main,
  },
  addCategoryModalContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '500px',
    backgroundColor: '#f3c3c3',
    boxShadow: 24,
    p: 3,
    borderRadius: 1,
  },
  addCategoryModalContentContainer: {
    display: 'flex',
    color: '#2c2c2c',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  addModalSubmitButton: {
    width: '6.2rem',
    color: '#ffffff',
    backgroundColor: '#2c2c2c',
    padding: 0,
    height: '2.6rem',
  },
  addModalCancelBtn: {
    width: '6.2rem',
    color: '#2c2c2c',
    backgroundColor: '#DBDBDB',
    padding: 0,
    height: '2.6rem',
  },
  addModalBtnContainer: {
    width: '46%',
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: '1rem',
    marginLeft: '50%',
  },
  addModalTitle: { color: '#2c2c2c', fontSize: '1.3rem' },
  deleteModalContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: '450px',
    bgcolor: '#ffffff',
    boxShadow: 24,
    borderRadius: 1,
    paddingBottom: 3,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  deleteModalConfirmText: {
    color: '#2c2c2c',
    fontWeight: 600,
    fontSize: '1.1rem',
  },
  deleteModalBtnContainer: {
    width: '50%',
    display: 'flex',
    justifyContent: 'space-between',
    mt: 2,
  },
  deleteModalCancelButton: {
    width: '6.2rem',
    color: '#2c2c2c',
    backgroundColor: '#DBDBDB',
    padding: 0,
    height: '2.6rem',
  },
  deleteModalConfirmButton: {
    width: '6.2rem',
    color: '#ffffff',
    backgroundColor: '#2c2c2c',
    padding: 0,
    height: '2.6rem',
  },
  deleteModalCancelIcon: {
    color: '#2c2c2c',
    marginLeft: '85%',
    marginTop: '1rem',
  },
});
export { categoryStyles };
