import { Theme } from '@mui/material';

export const planogramStyles = (theme: Theme) => ({
  deactivateButton: {
    color: theme.palette.primary.main,
  },
  headerContainer: {
    width: '100%',
    height: '9rem',
    display: 'flex',
    justifyContent: 'space-between',
    borderRadius: '0.5rem',
    backgroundColor: theme.palette.primary.main,
    alignItems: 'center',
    // position: 'sticky',
    // top: 70,
    // zIndex: 1,
  },
  searchAndMachineContainer: {
    width: '45%',
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginLeft: '1.7rem',
  },
  machineText: {
    marginLeft: '12px',
    fontSize: '15px',
    fontWeight: '500',
    marginBottom: '6px',
  },
  searchText: {
    marginLeft: '12px',
    fontSize: '15px',
    fontWeight: '500',
    marginBottom: '6px',
  },
  addMachineButtonContainer: {
    width: '22%',
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginRight: '1.7rem',
  },
  printerIcon: {
    color: theme.palette.text.primary,
    fontWeight: '200',
    fontSize: '2.7rem',
    border: `1px solid ${theme.palette.text.primary}`,
    borderRadius: '50%',
    padding: '6px',
  },
  planogramMainContainer: { width: '100%', marginTop: '2rem' },
  loadingIndicatorContainer: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '2rem',
    color: theme.palette.text.primary,
  },
  traysDataContainer: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    marginTop: '1rem',
  },
  trayHeaderContainer: {
    display: 'flex',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '0.6rem',
    padding: '0rem 0.7rem 0rem 0.3rem',
  },
  trayHeaderText: {
    fontWeight: '500',
    letterSpacing: '1px',
    fontSize: '15px',
  },
  trayHeaderDeactivateButton: {
    backgroundColor: theme.palette.error.dark,
    border: 'none',
    '&:hover': {
      backgroundColor: theme.palette.error.main,
      border: `1px solid`,
    },
  },
  trayDataParentContainer: {
    display: 'flex',
    alignItems: 'center',
    position: 'relative',
  },
  trayDataChild1Container: {
    position: 'relative',
    width: '99%',
    height: '11rem',
    display: 'flex',
    alignItems: 'center',
    gap: '1.5rem',
    paddingLeft: '0.6rem',
    paddingRight: '1.5rem',
    borderRadius: '0.5rem',
    backgroundColor: theme.palette.primary.main,
    overflow: 'hidden',
  },
  trayDataChild2Container: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 0,
    padding: 0,
    margin: 0,
  },
  leftScrollIcon: {
    position: 'absolute',
    left: -1,
    top: '40%',
    padding: 0,
    margin: 0,
    color: '#fff',
  },
  scrollIconFont: { fontSize: '2.6rem' },
  trayScrollContainer: {
    display: 'flex',
    gap: '1rem',
    overflowX: 'auto',
    scrollbarWidth: 'none',
    paddingLeft: '1rem',
    paddingRight: '1rem',
    '&::-webkit-scrollbar': {
      display: 'none',
    },
  },
  beltContainer: {
    width: '8rem',
    height: '9rem',
    padding: '6px',
    boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2), 0 6px 15px rgba(0, 0, 0, 0.1)',
    borderRadius: '0.5rem',
    display: 'flex',
    marginTop: '7px',
    flexDirection: 'column',
    justifyContent: 'center',
    marginBottom: '6px',
    alignItems: 'center',
    backgroundColor: theme.palette.primary.main,
  },
  beltSkuCodeText: { marginBottom: '6px', fontWeight: '500' },
  productImage: { width: '2rem', marginBottom: '0.5rem' },
  progressContainer: {
    width: '70%',
  },
  progressBar: {
    '&.MuiLinearProgress-root': {
      backgroundColor: theme.palette.text.primary,
      height: '8px',
      borderRadius: '8px',
      border: '1px solid #2c2c2c',
    },
    '& .MuiLinearProgress-bar': {
      backgroundColor: theme.palette.secondary.main,
      borderRadius: '3px',
      border: '1px solid #2c2c2c',
    },
  },
  quantityShowContainer: {
    width: '3.8rem',
    height: '1rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '1rem',
    textAlign: 'center',
    color: theme.palette.secondary.main,
    backgroundColor: theme.palette.text.primary,
    marginTop: '0.5rem',
  },
  rightIconButtonContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 0,
  },
  rightIconButton: {
    position: 'absolute',
    top: '39%',
    padding: 0,
    margin: 0,
    right: 8,
    color: '#fff',
  },
  addBeltIconButton: {
    padding: '0px',
    position: 'absolute',
    right: '-2px',
    top: '50%',
    transform: 'translateY(-50%)',
    borderRadius: '50%',
    backgroundColor: theme.palette.text.primary,
    color: theme.palette.primary.main,
  },
  addIcon: {
    '&:hover': {
      borderRadius: '50%',
      backgroundColor: theme.palette.text.primary,
      color: theme.palette.primary.main,
    },
  },
  dialog: {
    paddingTop: 0,
    marginTop: 0,
    color: theme.palette.primary.main,
    '& .MuiDialog-paper': {
      backgroundColor: '#fff',
      borderRadius: '8px',
    },
    '&.MuiDialog-root': {
      height: '38rem',
    },
  },
  dialogHeaderContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    color: theme.palette.primary.main,
    alignItems: 'center',
    padding: '0rem 0.5rem 0.1rem 1rem',
  },
  dialogTitle: { padding: 0, fontSize: '1.5rem' },
  dialogAction: {
    marginRight: '0.9rem',
    '&.MuiDialogActions-root': {
      paddingBottom: 0,
    },
  },
});
